import 'package:flutter/material.dart';

class Expedition {
  final String livraison,
      agenceDepart,
      expediteur,
      destinataire,
      villeExpediteur,
      villeDestinataire,
      codeExpedition,
      date,
      etat,
      villeDepart,
      villeArrivee;

  Expedition({
    @required this.agenceDepart,
    @required this.expediteur,
    @required this.destinataire,
    @required this.villeExpediteur,
    @required this.villeDestinataire,
    @required this.villeDepart,
    @required this.villeArrivee,
    @required this.codeExpedition,
    @required this.date,
    @required this.etat,
    @required this.livraison,
  });
}

List<Expedition> demoRecentExpeditions = [
  Expedition(
    codeExpedition: "56412",
    etat: "Livrée",
    villeDepart: "Meknes",
    date: "01-03-2021",
    villeArrivee: "Tanger",
    livraison: "A domicile",
    agenceDepart: "Casablanca",
    expediteur: "Zineb",
    destinataire: "fatin",
    villeExpediteur: "CASABLANCA",
    villeDestinataire: "MEKNES",
  ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
  //  Expedition(
  //   codeExpedition: "56412",
  //   etat: "Livrée",
  //   villeDepart: "Meknes",
  //   date: "01-03-2021",
  //   villeArrivee: "Tanger",
  //   livraison: "A domicile",
  //   agenceDepart: "Casablanca",
  //   expediteur: "Zineb",
  //   destinataire: "fatin",
  //   villeExpediteur: "CASABLANCA",
  //   villeDestinataire: "MEKNES",
  // ),
];
